openapi: 3.1.0
info:
  title: todos
  version: '1.0'
  summary: 'My test API '
  description: Test API description
  contact:
    name: Ondra Navratil
servers:
  - url: 'http://localhost:3000'
paths:
  /todo:
    post:
      summary: Create new TODO
      operationId: post-todo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/status'
                  data:
                    type: object
                    properties:
                      timestamp:
                        type: string
              examples:
                example1:
                  value:
                    status: success
                    data:
                      timestamp: TOTO JE EXAMPLE 1
                example2:
                  value:
                    status: fail
                    data:
                      timestamp: EXAMPLE 2
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                allOf:
                  - $ref: ../ErroResponse.yaml
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          errorSpecific:
                            type: object
                            properties:
                              someSpecialKey:
                                description: This is extension to the template
                                oneOf:
                                  - type: integer
                                    properties: {}
                                  - type: object
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    note:
                      type: string
                    id:
                      $ref: ../id.yaml
                  required:
                    - note
                    - id
      description: test
      tags:
        - TEST TAG
components:
  schemas:
    status:
      type: string
      title: status
      enum:
        - success
        - error
        - fail
        - lemon
      description: JSend response status
tags:
  - name: TEST TAG
